// GENERATED CODE - DO NOT MODIFY BY HAND
// Contains the static schema definition for Supabase tables.

import 'package:tether/schema/table_info.dart';

// ignore_for_file: prefer_single_quotes, unnecessary_brace_in_string_interps, unnecessary_string_interpolations

final Map<String, SupabaseTableInfo> globalSupabaseSchema = {
  'public.bookstores': SupabaseTableInfo(
    name: "bookstores",
    originalName: "bookstores",
    localName: "bookstores",
    schema: "public",
    columns: [
      SupabaseColumnInfo(
        name: "address",
        originalName: "address",
        localName: "address",
        type: "jsonb",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: null,
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "createdAt",
        originalName: "created_at",
        localName: "created_at",
        type: "timestamp with time zone",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: "now()",
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "establishedDate",
        originalName: "established_date",
        localName: "established_date",
        type: "date",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: null,
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "id",
        originalName: "id",
        localName: "id",
        type: "uuid",
        isNullable: false,
        isPrimaryKey: true,
        isUnique: false,
        defaultValue: "uuid_generate_v4()",
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "isOpen",
        originalName: "is_open",
        localName: "is_open",
        type: "boolean",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: "true",
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "name",
        originalName: "name",
        localName: "name",
        type: "text",
        isNullable: false,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: null,
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "updatedAt",
        originalName: "updated_at",
        localName: "updated_at",
        type: "timestamp with time zone",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: "now()",
        comment: null,
      ),
    ],
    foreignKeys: [
    ],
    indexes: [
      SupabaseIndexInfo(
        name: "bookstoresPkey",
        originalName: "bookstores_pkey",
        localName: "bookstoresPkey",
        isUnique: true,
        columns: ["id"],
        originalColumns: ["id"],
      ),
      SupabaseIndexInfo(
        name: "idxBookstoresName",
        originalName: "idx_bookstores_name",
        localName: "idxBookstoresName",
        isUnique: false,
        columns: ["name"],
        originalColumns: ["name"],
      ),
    ],
    comment: null,
  ),
  'public.authors': SupabaseTableInfo(
    name: "authors",
    originalName: "authors",
    localName: "authors",
    schema: "public",
    columns: [
      SupabaseColumnInfo(
        name: "bio",
        originalName: "bio",
        localName: "bio",
        type: "text",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: null,
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "birthDate",
        originalName: "birth_date",
        localName: "birth_date",
        type: "date",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: null,
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "createdAt",
        originalName: "created_at",
        localName: "created_at",
        type: "timestamp with time zone",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: "now()",
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "deathDate",
        originalName: "death_date",
        localName: "death_date",
        type: "date",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: null,
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "document",
        originalName: "document",
        localName: "document",
        type: "tsvector",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: null,
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "firstName",
        originalName: "first_name",
        localName: "first_name",
        type: "text",
        isNullable: false,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: null,
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "id",
        originalName: "id",
        localName: "id",
        type: "uuid",
        isNullable: false,
        isPrimaryKey: true,
        isUnique: false,
        defaultValue: "uuid_generate_v4()",
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "lastName",
        originalName: "last_name",
        localName: "last_name",
        type: "text",
        isNullable: false,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: null,
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "updatedAt",
        originalName: "updated_at",
        localName: "updated_at",
        type: "timestamp with time zone",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: "now()",
        comment: null,
      ),
    ],
    foreignKeys: [
    ],
    indexes: [
      SupabaseIndexInfo(
        name: "authorsPkey",
        originalName: "authors_pkey",
        localName: "authorsPkey",
        isUnique: true,
        columns: ["id"],
        originalColumns: ["id"],
      ),
      SupabaseIndexInfo(
        name: "idxAuthorsFullTextSearch",
        originalName: "idx_authors_full_text_search",
        localName: "idxAuthorsFullTextSearch",
        isUnique: false,
        columns: ["document"],
        originalColumns: ["document"],
      ),
      SupabaseIndexInfo(
        name: "idxAuthorsLastName",
        originalName: "idx_authors_last_name",
        localName: "idxAuthorsLastName",
        isUnique: false,
        columns: ["lastName"],
        originalColumns: ["last_name"],
      ),
    ],
    comment: null,
  ),
  'public.genres': SupabaseTableInfo(
    name: "genres",
    originalName: "genres",
    localName: "genres",
    schema: "public",
    columns: [
      SupabaseColumnInfo(
        name: "createdAt",
        originalName: "created_at",
        localName: "created_at",
        type: "timestamp with time zone",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: "now()",
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "description",
        originalName: "description",
        localName: "description",
        type: "text",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: null,
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "id",
        originalName: "id",
        localName: "id",
        type: "uuid",
        isNullable: false,
        isPrimaryKey: true,
        isUnique: false,
        defaultValue: "uuid_generate_v4()",
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "name",
        originalName: "name",
        localName: "name",
        type: "text",
        isNullable: false,
        isPrimaryKey: false,
        isUnique: true,
        defaultValue: null,
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "updatedAt",
        originalName: "updated_at",
        localName: "updated_at",
        type: "timestamp with time zone",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: "now()",
        comment: null,
      ),
    ],
    foreignKeys: [
    ],
    indexes: [
      SupabaseIndexInfo(
        name: "genresNameKey",
        originalName: "genres_name_key",
        localName: "genresNameKey",
        isUnique: true,
        columns: ["name"],
        originalColumns: ["name"],
      ),
      SupabaseIndexInfo(
        name: "genresPkey",
        originalName: "genres_pkey",
        localName: "genresPkey",
        isUnique: true,
        columns: ["id"],
        originalColumns: ["id"],
      ),
      SupabaseIndexInfo(
        name: "idxGenresName",
        originalName: "idx_genres_name",
        localName: "idxGenresName",
        isUnique: false,
        columns: ["name"],
        originalColumns: ["name"],
      ),
    ],
    comment: null,
  ),
  'public.images': SupabaseTableInfo(
    name: "images",
    originalName: "images",
    localName: "images",
    schema: "public",
    columns: [
      SupabaseColumnInfo(
        name: "altText",
        originalName: "alt_text",
        localName: "alt_text",
        type: "text",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: null,
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "createdAt",
        originalName: "created_at",
        localName: "created_at",
        type: "timestamp with time zone",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: "now()",
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "id",
        originalName: "id",
        localName: "id",
        type: "uuid",
        isNullable: false,
        isPrimaryKey: true,
        isUnique: false,
        defaultValue: "uuid_generate_v4()",
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "updatedAt",
        originalName: "updated_at",
        localName: "updated_at",
        type: "timestamp with time zone",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: "now()",
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "url",
        originalName: "url",
        localName: "url",
        type: "text",
        isNullable: false,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: null,
        comment: null,
      ),
    ],
    foreignKeys: [
    ],
    indexes: [
      SupabaseIndexInfo(
        name: "imagesPkey",
        originalName: "images_pkey",
        localName: "imagesPkey",
        isUnique: true,
        columns: ["id"],
        originalColumns: ["id"],
      ),
    ],
    comment: null,
  ),
  'public.books': SupabaseTableInfo(
    name: "books",
    originalName: "books",
    localName: "books",
    schema: "public",
    columns: [
      SupabaseColumnInfo(
        name: "authorId",
        originalName: "author_id",
        localName: "author_id",
        type: "uuid",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: null,
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "bannerImageId",
        originalName: "banner_image_id",
        localName: "banner_image_id",
        type: "uuid",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: null,
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "coverImageId",
        originalName: "cover_image_id",
        localName: "cover_image_id",
        type: "uuid",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: null,
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "createdAt",
        originalName: "created_at",
        localName: "created_at",
        type: "timestamp with time zone",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: "now()",
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "description",
        originalName: "description",
        localName: "description",
        type: "text",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: null,
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "document",
        originalName: "document",
        localName: "document",
        type: "tsvector",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: null,
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "id",
        originalName: "id",
        localName: "id",
        type: "uuid",
        isNullable: false,
        isPrimaryKey: true,
        isUnique: false,
        defaultValue: "uuid_generate_v4()",
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "metadata",
        originalName: "metadata",
        localName: "metadata",
        type: "jsonb",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: null,
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "price",
        originalName: "price",
        localName: "price",
        type: "numeric",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: null,
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "publicationDate",
        originalName: "publication_date",
        localName: "publication_date",
        type: "date",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: null,
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "stockCount",
        originalName: "stock_count",
        localName: "stock_count",
        type: "integer",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: "0",
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "tags",
        originalName: "tags",
        localName: "tags",
        type: "ARRAY",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: null,
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "title",
        originalName: "title",
        localName: "title",
        type: "text",
        isNullable: false,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: null,
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "updatedAt",
        originalName: "updated_at",
        localName: "updated_at",
        type: "timestamp with time zone",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: false,
        defaultValue: "now()",
        comment: null,
      ),
    ],
    foreignKeys: [
      SupabaseForeignKeyConstraint(
        constraintName: "books_author_id_fkey",
        columns: ["authorId"],
        originalColumns: ["author_id"],
        localColumns: ["author_id"],
        foreignTableSchema: "public",
        foreignTableName: "authors",
        originalForeignTableName: "authors",
        localForeignTableName: "authors",
        foreignColumns: ["id"],
        originalForeignColumns: ["id"],
        localForeignColumns: ["id"],
        updateRule: "NO ACTION",
        deleteRule: "SET NULL",
        matchOption: "NONE",
        isDeferrable: false,
        initiallyDeferred: false,
        joinTableName: null,
      ),
      SupabaseForeignKeyConstraint(
        constraintName: "books_banner_image_id_fkey",
        columns: ["bannerImageId"],
        originalColumns: ["banner_image_id"],
        localColumns: ["banner_image_id"],
        foreignTableSchema: "public",
        foreignTableName: "images",
        originalForeignTableName: "images",
        localForeignTableName: "images",
        foreignColumns: ["id"],
        originalForeignColumns: ["id"],
        localForeignColumns: ["id"],
        updateRule: "NO ACTION",
        deleteRule: "SET NULL",
        matchOption: "NONE",
        isDeferrable: false,
        initiallyDeferred: false,
        joinTableName: null,
      ),
      SupabaseForeignKeyConstraint(
        constraintName: "books_cover_image_id_fkey",
        columns: ["coverImageId"],
        originalColumns: ["cover_image_id"],
        localColumns: ["cover_image_id"],
        foreignTableSchema: "public",
        foreignTableName: "images",
        originalForeignTableName: "images",
        localForeignTableName: "images",
        foreignColumns: ["id"],
        originalForeignColumns: ["id"],
        localForeignColumns: ["id"],
        updateRule: "NO ACTION",
        deleteRule: "SET NULL",
        matchOption: "NONE",
        isDeferrable: false,
        initiallyDeferred: false,
        joinTableName: null,
      ),
    ],
    indexes: [
      SupabaseIndexInfo(
        name: "booksPkey",
        originalName: "books_pkey",
        localName: "booksPkey",
        isUnique: true,
        columns: ["id"],
        originalColumns: ["id"],
      ),
      SupabaseIndexInfo(
        name: "idxBooksFullTextSearch",
        originalName: "idx_books_full_text_search",
        localName: "idxBooksFullTextSearch",
        isUnique: false,
        columns: ["document"],
        originalColumns: ["document"],
      ),
      SupabaseIndexInfo(
        name: "idxBooksPublicationDate",
        originalName: "idx_books_publication_date",
        localName: "idxBooksPublicationDate",
        isUnique: false,
        columns: ["publicationDate"],
        originalColumns: ["publication_date"],
      ),
      SupabaseIndexInfo(
        name: "idxBooksTitle",
        originalName: "idx_books_title",
        localName: "idxBooksTitle",
        isUnique: false,
        columns: ["title"],
        originalColumns: ["title"],
      ),
    ],
    comment: null,
  ),
  'public.book_genres': SupabaseTableInfo(
    name: "bookGenres",
    originalName: "book_genres",
    localName: "book_genres",
    schema: "public",
    columns: [
      SupabaseColumnInfo(
        name: "bookId",
        originalName: "book_id",
        localName: "book_id",
        type: "uuid",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: true,
        defaultValue: null,
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "genreId",
        originalName: "genre_id",
        localName: "genre_id",
        type: "uuid",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: true,
        defaultValue: null,
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "id",
        originalName: "id",
        localName: "id",
        type: "integer",
        isNullable: false,
        isPrimaryKey: true,
        isUnique: false,
        defaultValue: "nextval('book_genres_id_seq'::regclass)",
        comment: null,
      ),
    ],
    foreignKeys: [
      SupabaseForeignKeyConstraint(
        constraintName: "book_genres_book_id_fkey",
        columns: ["bookId"],
        originalColumns: ["book_id"],
        localColumns: ["book_id"],
        foreignTableSchema: "public",
        foreignTableName: "books",
        originalForeignTableName: "books",
        localForeignTableName: "books",
        foreignColumns: ["id"],
        originalForeignColumns: ["id"],
        localForeignColumns: ["id"],
        updateRule: "NO ACTION",
        deleteRule: "CASCADE",
        matchOption: "NONE",
        isDeferrable: false,
        initiallyDeferred: false,
        joinTableName: "book_genres",
      ),
      SupabaseForeignKeyConstraint(
        constraintName: "book_genres_genre_id_fkey",
        columns: ["genreId"],
        originalColumns: ["genre_id"],
        localColumns: ["genre_id"],
        foreignTableSchema: "public",
        foreignTableName: "genres",
        originalForeignTableName: "genres",
        localForeignTableName: "genres",
        foreignColumns: ["id"],
        originalForeignColumns: ["id"],
        localForeignColumns: ["id"],
        updateRule: "NO ACTION",
        deleteRule: "CASCADE",
        matchOption: "NONE",
        isDeferrable: false,
        initiallyDeferred: false,
        joinTableName: "book_genres",
      ),
    ],
    indexes: [
      SupabaseIndexInfo(
        name: "bookGenresBookIdGenreIdKey",
        originalName: "book_genres_book_id_genre_id_key",
        localName: "bookGenresBookIdGenreIdKey",
        isUnique: true,
        columns: ["bookId", "genreId"],
        originalColumns: ["book_id", "genre_id"],
      ),
      SupabaseIndexInfo(
        name: "bookGenresPkey",
        originalName: "book_genres_pkey",
        localName: "bookGenresPkey",
        isUnique: true,
        columns: ["id"],
        originalColumns: ["id"],
      ),
      SupabaseIndexInfo(
        name: "idxBookGenresBookId",
        originalName: "idx_book_genres_book_id",
        localName: "idxBookGenresBookId",
        isUnique: false,
        columns: ["bookId"],
        originalColumns: ["book_id"],
      ),
      SupabaseIndexInfo(
        name: "idxBookGenresGenreId",
        originalName: "idx_book_genres_genre_id",
        localName: "idxBookGenresGenreId",
        isUnique: false,
        columns: ["genreId"],
        originalColumns: ["genre_id"],
      ),
    ],
    comment: null,
  ),
  'public.bookstore_books': SupabaseTableInfo(
    name: "bookstoreBooks",
    originalName: "bookstore_books",
    localName: "bookstore_books",
    schema: "public",
    columns: [
      SupabaseColumnInfo(
        name: "bookId",
        originalName: "book_id",
        localName: "book_id",
        type: "uuid",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: true,
        defaultValue: null,
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "bookstoreId",
        originalName: "bookstore_id",
        localName: "bookstore_id",
        type: "uuid",
        isNullable: true,
        isPrimaryKey: false,
        isUnique: true,
        defaultValue: null,
        comment: null,
      ),
      SupabaseColumnInfo(
        name: "id",
        originalName: "id",
        localName: "id",
        type: "integer",
        isNullable: false,
        isPrimaryKey: true,
        isUnique: false,
        defaultValue: "nextval('bookstore_books_id_seq'::regclass)",
        comment: null,
      ),
    ],
    foreignKeys: [
      SupabaseForeignKeyConstraint(
        constraintName: "bookstore_books_book_id_fkey",
        columns: ["bookId"],
        originalColumns: ["book_id"],
        localColumns: ["book_id"],
        foreignTableSchema: "public",
        foreignTableName: "books",
        originalForeignTableName: "books",
        localForeignTableName: "books",
        foreignColumns: ["id"],
        originalForeignColumns: ["id"],
        localForeignColumns: ["id"],
        updateRule: "NO ACTION",
        deleteRule: "CASCADE",
        matchOption: "NONE",
        isDeferrable: false,
        initiallyDeferred: false,
        joinTableName: "bookstore_books",
      ),
      SupabaseForeignKeyConstraint(
        constraintName: "bookstore_books_bookstore_id_fkey",
        columns: ["bookstoreId"],
        originalColumns: ["bookstore_id"],
        localColumns: ["bookstore_id"],
        foreignTableSchema: "public",
        foreignTableName: "bookstores",
        originalForeignTableName: "bookstores",
        localForeignTableName: "bookstores",
        foreignColumns: ["id"],
        originalForeignColumns: ["id"],
        localForeignColumns: ["id"],
        updateRule: "NO ACTION",
        deleteRule: "CASCADE",
        matchOption: "NONE",
        isDeferrable: false,
        initiallyDeferred: false,
        joinTableName: "bookstore_books",
      ),
    ],
    indexes: [
      SupabaseIndexInfo(
        name: "bookstoreBooksBookstoreIdBookIdKey",
        originalName: "bookstore_books_bookstore_id_book_id_key",
        localName: "bookstoreBooksBookstoreIdBookIdKey",
        isUnique: true,
        columns: ["bookstoreId", "bookId"],
        originalColumns: ["bookstore_id", "book_id"],
      ),
      SupabaseIndexInfo(
        name: "bookstoreBooksPkey",
        originalName: "bookstore_books_pkey",
        localName: "bookstoreBooksPkey",
        isUnique: true,
        columns: ["id"],
        originalColumns: ["id"],
      ),
      SupabaseIndexInfo(
        name: "idxBookstoreBooksBookId",
        originalName: "idx_bookstore_books_book_id",
        localName: "idxBookstoreBooksBookId",
        isUnique: false,
        columns: ["bookId"],
        originalColumns: ["book_id"],
      ),
      SupabaseIndexInfo(
        name: "idxBookstoreBooksBookstoreId",
        originalName: "idx_bookstore_books_bookstore_id",
        localName: "idxBookstoreBooksBookstoreId",
        isUnique: false,
        columns: ["bookstoreId"],
        originalColumns: ["bookstore_id"],
      ),
    ],
    comment: null,
  ),
};
